-- INSERT INTO masters (STATUS, STATUS_DESC, DETAIL_SEQ_ID, DESCRIPTION)
-- VALUES (1, "None", 1, "Severity"),
-- (2, "Low", 1, "Severity"),
-- (3, "High", 1, "Severity"),
-- (1, "Personal", 2, "Category"),
-- (2, "Work", 2, "Category"),
-- (1, "New", 3, "Status"),
-- (2, "In Progress", 3, "Status"),
-- (3, "Completed", 3, "Status")

INSERT INTO masters (DT_CODE, DT_DESCRIPTION, DETAIL_SEQ_ID, DESCRIPTION)
VALUES (1, "New", 3, "Status"),
(2, "In Progress", 3, "Status"),
(3, "Completed", 3, "Status")

SELECT * FROM tasks;
SELECT * FROM masters; 

SELECT TASK_ID, TITLE, A.DT_DESCRIPTION, STATUS, 
B.DT_DESCRIPTION AS STATUS_DESC, SEVERITY, C.DESCRIPTION AS SEVERITY_DESC, 
CATEGORY, D.DESCRIPTION AS CATEGORY_DESC, TASK_DATE

SELECT TASK_ID, TITLE, A.DESCRIPTION, STATUS, 
B.DT_DESCRIPTION AS STATUS_DESC, SEVERITY, C.DT_DESCRIPTION AS SEVERITY_DESC, 
CATEGORY, D.DT_DESCRIPTION AS CATEGORY_DESC, TASK_DATE
FROM tasks A
LEFT JOIN masters B ON A.STATUS = B.DT_CODE AND B.DETAIL_SEQ_ID = 3
LEFT JOIN masters C ON A.SEVERITY = C.DT_CODE AND C.DETAIL_SEQ_ID = 1
LEFT JOIN masters D ON A.CATEGORY = D.DT_CODE  AND D.DETAIL_SEQ_ID = 2
WHERE USER_ID=8 ORDER BY TASK_ID DESC;


